runtime: python311

# Cloud Run service configuration
service: tradewise-backend

# Environment variables (you can also set these in Cloud Run UI)
env_variables:
  PORT: "8080"

# Scaling configuration
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.8

# Resources
resources:
  cpu: 1
  memory_gb: 2

# Timeout
entrypoint: uvicorn main:app --host 0.0.0.0 --port $PORT
